### ISSUE TITLE
failed to run the demo due to ImportError

### ISSUE THREAD

**Issue by zxypetre** [wechaty/python-wechaty-puppet-padplus#1]
ImportError: cannot import name 'HostiePuppet' from 'wechaty_puppet_padplus.puppet'

**Comment by wj-Mcat** [comment]
This repo is at init stage, which can't run well. We try to make it runnable as soon as possiable. Thanks for using. Please keep eyes on this repo.

**Comment by zxypetre** [comment]
that's ok, thanks for your reply, do you mean that the wechaty of python doesn't support the pad protocol ?

**Comment by wj-Mcat** [comment]
Yes，but just now, not in the days later. Please keey eyes on this repo. You can watch this repo to get the latest news about `python-wechaty-puppet-padplus`. Thanks you for your attention.

**Comment by jcai** [comment]
@zxypetre you can try scala-wechaty which supports padplus token.
